import pandas as pd
from fpdf import FPDF
import os

# ตั้งค่าเส้นทางไปยังไฟล์ CSV
data_file_path = "data/sales_data.csv"

# ตรวจสอบว่ามีไฟล์ CSV หรือไม่
if not os.path.exists(data_file_path):
    print("Data file not found!")
    exit()

# อ่านข้อมูลจาก CSV
df = pd.read_csv(data_file_path)

# ประมวลผลข้อมูล (ตัวอย่าง: สรุปยอดขายรายเดือน)
summary = df.groupby("Month")["Sales"].sum().reset_index()

# ตรวจสอบว่ามีโฟลเดอร์ reports หรือไม่ ถ้าไม่มีให้สร้างใหม่
if not os.path.exists("reports"):
    os.makedirs("reports")

# สร้างคลาส FPDF ที่ปรับแต่งรูปแบบใหม่
class PDFReport(FPDF):
    def header(self):
        # กำหนดพื้นหลังสีหัวเรื่องให้ดูทันสมัย
        self.set_fill_color(33, 150, 243)  # สีฟ้าทันสมัย
        self.rect(0, 0, self.w, 40, 'F')
        
        # ตั้งค่าฟอนต์หัวเรื่อง
        self.set_font("Arial", "B", 18)
        self.set_text_color(255, 255, 255)  # ข้อความสีขาว
        self.cell(0, 30, "Monthly Sales Report", ln=True, align="C")
        
        # คำอธิบายรายงาน
        self.set_font("Arial", "I", 12)
        self.cell(0, 10, "Generated by Report Generator Bot", ln=True, align="C")
        self.cell(0, 10, "", ln=True)  # เว้นบรรทัด

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(150, 150, 150)  # สีเทาอ่อน
        self.cell(0, 10, f"Page {self.page_no()}", 0, 0, "C")

    def add_table(self, data):
        # คำนวณจุดเริ่มต้นเพื่อให้ตารางอยู่ตรงกลาง
        table_width = 160
        start_x = (self.w - table_width) / 2
        self.set_x(start_x)

        # สร้างหัวตาราง
        self.set_fill_color(63, 81, 181)  # สีพื้นหลังฟ้าเข้ม
        self.set_text_color(255, 255, 255)  # ข้อความสีขาว
        self.set_font("Arial", "B", 12)
        self.cell(80, 10, "Month", 1, 0, "C", fill=True)
        self.cell(80, 10, "Total Sales", 1, 1, "C", fill=True)

        # เพิ่มข้อมูลในตาราง
        self.set_text_color(0, 0, 0)  # ข้อความสีดำ
        self.set_font("Arial", "", 12)
        fill = False
        for index, row in data.iterrows():
            self.set_x(start_x)  # กำหนดตำแหน่ง X สำหรับแต่ละแถวของตาราง
            self.cell(80, 10, row["Month"], 1, 0, "C", fill=fill)
            self.cell(80, 10, f"${row['Sales']:.2f}", 1, 1, "C", fill=fill)
          #   fill = not fill  # สลับสีพื้นหลังระหว่างแถว

        self.cell(0, 10, "", ln=True)  # เว้นบรรทัด

    def add_summary(self, data):
        total_sales = data["Sales"].sum()
        self.set_text_color(33, 150, 243)  # ใช้สีฟ้าทันสมัยสำหรับข้อความ
        self.set_font("Arial", "B", 14)
        self.cell(0, 10, f"Total Sales for All Months: ${total_sales:.2f}", ln=True, align="C")

# สร้างไฟล์ PDF รายงาน
pdf = PDFReport()
pdf.add_page()

# เพิ่มตารางข้อมูลและสรุปยอดขาย
pdf.add_table(summary)
pdf.add_summary(summary)

# บันทึก PDF
pdf_output_path = "reports/sales_report.pdf"
pdf.output(pdf_output_path)
print(f"Report has been saved to {pdf_output_path}")
